#
# Copyright (c) 2017, 2020 ADLINK Technology Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ADLINK zenoh team, <zenoh@adlink-labs.tech>
#
[package]
name = "zplugin-mqtt"
version = "0.6.0-beta.1"
authors = [
    "Julien Enoch <julien@enoch.fr>",
]
edition = "2018"
repository = "https://github.com/eclipse-zenoh/zenoh-plugin-mqtt"
homepage = "http://zenoh.io"
license = " EPL-2.0 OR Apache-2.0"
categories = ["network-programming"]
description = "Zenoh plugin for MQTT"

[lib]
name = "zplugin_mqtt"
crate-type = ["cdylib", "rlib"]

[features]
no_mangle = ["zenoh-plugin-trait/no_mangle"]
default = ["no_mangle"]

[dependencies]
zenoh = { version = "0.6.0-beta.1", features = ["unstable"] }
zenoh-collections = { version = "0.6.0-beta.1" }
zenoh-core = { version = "0.6.0-beta.1" }
zenoh-ext = { version = "0.6.0-beta.1", features = ["unstable"] }
zenoh-plugin-trait = { version = "0.6.0-beta.1", default-features = false }
async-trait = "0.1.57"
derivative = "2.2.0"
env_logger = "0.9.1"
flume = "0.10.14"
futures = "0.3.24"
git-version = "0.3.5"
hex = "0.4.3"
lazy_static = "1.4.0"
log = "0.4.17"
regex = "1.6.0"
serde = "1.0.144"
serde_json = "1.0.85"
ntex-mqtt = "0.8"
ntex = { version = "0.5", features = ["async-std", "rustls"] }

[dependencies.async-std]
version = "=1.12.0"
features = ["unstable", "attributes"]

[build-dependencies]
rustc_version = "0.4"

[package.metadata.deb]
name = "zenoh-plugin-mqtt"
maintainer = "zenoh-dev@eclipse.org"
copyright = "2017, 2020 ADLINK Technology Inc."
section = "net"
license-file = ["LICENSE", "0"]
depends = "zenohd (=0.6.0-beta.1)"
